### ISSUE TITLE
[BUG] v1.9.4 Causing Crash of Homebridge

### ISSUE THREAD

**Issue by plutod73** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#104]
[homebridge.log.txt](https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/files/6837047/homebridge.log.txt)

### Describe the bug
Upgraded from v1.9.2 to 1.9.4 and Homebridge will not boot. Continuously retries yielding the error:
```
[7/18/2021, 6:25:14 PM] [homebridge-magichome-dynamic-platform] Initializing homebridge-magichome-dynamic-platform platform...
[7/18/2021, 6:25:14 PM] TypeError: Cannot read property 'logLevel' of undefined
    at new HomebridgeMagichomeDynamicPlatform (/usr/local/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:59:37)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
[7/18/2021, 6:25:14 PM] Got SIGTERM, shutting down Homebridge...
```

Reverting back to 1.9.2 corrects the issue. Running home bridge on macOS with latest versions of everything else.

### To Reproduce
e.g.
1. In Homebridge web UI, navigate to Plugins
2. Select "UPDATE" for the "Homebridge MagicHome Dynamic Platform"
3. Reboot Homebridge server after update completes, Homebridge is now stuck in a loop giving the above error message.

### Expected behavior
Expected it to permit Homebridge to boot and run as it did with v1.9.2.

#### Host Hardware
* Hardware: macMini M1
* OS: MacOS Big Sur
* OS Version: 11.4

#### Homebridge and MagicHome 
* Homebridge 1.3.4
* Homebridge MagicHome Dynamic Platform version 1.9.2 (works) / 1.9.4 (doesn't work)
* Link to the MagicHome Device on the seller's website: N/A

**Comment by muzzymate** [comment]
I am seeing this behavior as well where it will crash the childbridge running the MagicHome plugin  repeatedly. Reverted back to 1.9.3b13 and back to operational status.

**Comment by JonyBCN** [comment]
Same here on a Docker.

**Comment by plutod73** [comment]
Oddly enough, I tried upgrading from 1.9.2 to 1.9.3b13 and I receive the same error as with 1.9.4. Reverted back to 1.9.2 and everything is good again.

I also tried upgrading to 1.9.3a4, with no success either. Seems like the issue may not be the build, but the upgrade from a prior working version?

**Comment by John88a** [comment]
I have the same issue today, reverted back to 1.9.2 and working again.

**Comment by bwp91** [comment]
Use the homebridge UI to set a log level… and restart.

**Comment by bwp91** [comment]
It's the very last option on the plug-in settings screen,

![image](https://user-images.githubusercontent.com/43026681/136851369-da34aac2-4e68-4cc8-84db-b15e92507541.jpeg)

**Comment by mreassassin** [comment]
interesting..  I don't have that Log Level option...  is there a way to force it in the config file?

**Comment by Zacknetic** [comment]
Hello, I have made a change that prevents a missing config option from crashing Homebridge. I will mark this as solved, but please feel free to open another issue if a similar problem occurs.

Thank you.
-z
