### ISSUE TITLE
[ISSUE] LEDNET lightstrip not connecting

### ISSUE THREAD

**Issue by charliekmcmahon** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#105]
![image](https://user-images.githubusercontent.com/51872183/127153697-a2256674-a31d-4da6-bb73-ee63fa3c2d8f.jpeg)

Fresh install of homebridge and the plug-in installed. I'm not sure what the issue could be.

**Comment by Zacknetic** [comment]
This usually happens when a device is behind a different subnet (such as a secondary router) or when using Docker. Are either of these scenarios the case?

**Comment by iRayanKhan** [comment]
> This usually happens when a device is behind a different subnet (such as a secondary router) or when using Docker. Are either of these scenarios the case?

Mine is behind a secondary router, and suddenly the plugin will report "No Response" for every device, when I try to control any device. Most of my devices are behind a main router.

**Comment by Zacknetic** [comment]
@iRayanKhan @charliekmcmahon

Hello, please update to version 1.9.7 and ensure you are upgraded to node 16. This should fix your issues.

Please let me know.
-z

**Comment by Zacknetic** [comment]
Closing this issue as solved.
