### ISSUE TITLE
Does anyone review this?

### ISSUE THREAD

**Issue by Biggsylad** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#106]
Plugin is very buggy and unresponsive

**Comment by Zacknetic** [comment]
Hi,

The "Issues" section of this repository is used to describe Issues/Requests. Please take a look at the currently open issues and see any describe the one you are facing. If the Issue report already exists then I am aware of it and will solve it when I can spare the time towards labor hours. If you do not find your Issue feel free to create a new post using the "Bug Report" template (click the "Get Started" button) and fill out the required information. 

Good day.
