### ISSUE TITLE
Not able to add lights to Homebridge

### ISSUE THREAD

**Issue by EzzatQ** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#108]
### Logs
1. Enable debug mode in Homebridge
1. Reproduce the issue so that it appears in the logs
1. Upload a '.txt' file of your logs to this issue. ( Logs from screenshots, in '.rtf' format, or pasted directly into the post make debugging extremely difficult. Please just upload the file. )

### Describe the bug
Not able to add lights to homebridge.
I get the following Error:
```
Warning! Discovered device did not respond to query. This is usually due to an unresponsive device.
Please restart homebridge. If the problem persists, ensure the device works in the "Magichome Pro" app.
File an issue on github with an uploaded log. {
  ipAddress: 'x.x.x.x',
  uniqueId: 'xxxxxxxxxxxx"
  modelNumber: 'AK001-ZJ200'
}
```

### To Reproduce
e.g.
1. Clean install of homebridge on macOs
2. Add magichome plugin
3. restart
4. see logs

### Expected behavior
Expected the devices to be added normally

#### Host Hardware
* Hardware: Macbook pro 2015
* OS: MacOs
* OS Version: 11.5.2

#### Homebridge and MagicHome 
* Homebridge 1.3.5
* Homebridge MagicHome Dynamic Platform version 1.9.4

#### Screenshots
[homebridge.log](https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/files/7340662/homebridge.log)

**Comment by EzzatQ** [comment]
Any news?

**Comment by Zacknetic** [comment]
Hello, please update to version 1.9.7 and ensure you are upgraded to node 16. This should fix your issues.

Please let me know.

**Comment by EzzatQ** [comment]
That fixed it! Thank you
