### ISSUE TITLE
[BUG] Concise Description of the Issue

### ISSUE THREAD

**Issue by coopchri** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#109]
[10/31/2021, 10:24:12 PM] [homebridge-magichome-dynamic-platform] Warning! Discovered device did not respond to query. This is usually due to an unresponsive device.
Please restart homebridge. If the problem persists, ensure the device works in the "Magichome Pro" app.
File an issue on github with an uploaded log. {
  ipAddress: '192.
  uniqueId: '10521CFF11A1',
  modelNumber: 'AK001-ZJ2101'

}

I always get this error when trying to use. It is annoying as it works with magic home pro and I am trying to switch to homepod Mini from Google Home.

**Comment by majornicety** [comment]
I also have this very same issue.

**Comment by RuntyCascade** [comment]
Same

**Comment by bwp91** [comment]
and me!

**Comment by Zacknetic** [comment]
Howdy, the new version of node that Homebridge updated to has broken my plugin. I am planning a beta major-version release on Sunday. However, I have just realized that my dev environment was not using node 16. I have just updated and now am tracking down the problem.

**Comment by Zacknetic** [comment]
@coopchri @RuntyCascade @majornicety @bwp91 
Hello, please update to version 1.9.7 and ensure you are upgraded to node 16. This should fix your issues.

Please let me know.
-z

**Comment by majornicety** [comment]
> I also have this very same issue.

All fixed for me. Thanks

**Comment by Zacknetic** [comment]
Closing this issue as solved.
