### ISSUE TITLE
[BUG] Concise Description of the Issue

### ISSUE THREAD

**Issue by Damianod27** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#110]
Hello. Since my few plugins required the installation of a new version of Node.js and NPM. I updated them today. From now on, the MagicHome lights control in homebridge and the Home application do not work. There are no log errors. Everything looks fine but the lights don't react.

Homebridge Vesrion : 1.35
Nodejs Version : 16.13.0
NPM Version : 8.1.0
MagicHome Version : 1.9.,4

**Comment by dakovacic** [comment]
I am also seeing this issue since my upgrade of Node.js to 16.13.0.

Homebridge Version : 1.35
Nodejs Version : 16.13.0
NPM Version : 8.1.0
MagicHome Version : 1.9.4

Turning the plugin logging level up to trace indicates that the plugin sees and registers my devices on initial startup, but then can't talk to them and goes into a loop of trying to rediscover them.

**Comment by monteroman** [comment]
I'm also seeing this behavior on the same versions. 
All of my MagicLight color bulbs are showing 100% brightness and turned on in My Home, however they are all powered off.  They all respond normally with the MagicLight mobile app.

**Comment by Damianod27** [comment]
Yes, that's right.  This is a Node.js 16.13.0 problem.  Some of my plugins require a new Node.js.  They are more important to me.  That's why he stays with the new version.  Because they solve the problem in my plugins.  I am waiting for the problem to be solved.  It is a pity that so many days pass and nobody wants to be interested in it.

**Comment by Zacknetic** [comment]
Hi, 

node has broken this plugin as you have deducted. It is not that I do not care about this plugin, I fact I have been developing a complete overhaul since august. I plan to push a beta on Sunday. Please join the discord and inquire if you are interested.

**Comment by Damianod27** [comment]
Hello Zacinetic.  Thank you for your answer.  Nobody said you weren't interested in the plug.  My point was that no one was interested in the reported problem.  You release updates.  Nobody requires you to fix the bug within seconds.  You're doing a good job.  Thank you for your plugin.  We are waiting calmly for the updates.

**Comment by Zacknetic** [comment]
I can’t wait to bring it to you. Thank you for your patience!

**Comment by Zacknetic** [comment]
Hello, please update to version 1.9.7 and ensure you are upgraded to node 16. This should fix your issues.

Please let me know.
-z

**Comment by monteroman** [comment]
1.9.7 was working up until the last home bridge update came out last week.  HB 1.3.8, Node 13.16.1.  It's doing the same thing as it was before.  You click the button on, nothing happens, but the Home app thinks it is on.

**Comment by Zacknetic** [comment]
> 1.9.7 was working up until the last home bridge update came out last week. HB 1.3.8, Node 13.16.1. It's doing the same thing as it was before. You click the button on, nothing happens, but the Home app thinks it is on.

Homebridge does not support odd-numbered releases of Node.js. Can you confirm that you are using Node 13.16.1 and if so, please update to 14.x  or 16.x. Let me know how that goes.

**Comment by monteroman** [comment]
Sorry, i reversed the #’s.  It was actually 16.13.1, not 13.16.1.

**Comment by Zacknetic** [comment]
Testing.

**Comment by Zacknetic** [comment]
I just tested it on:

Node.js Version | v16.13.1
Homebridge Version | v1.3.8

It is working correctly.

I will close this as it seems the original issue has been solved. @monteroman, please create a new issue using and following the bug template. The more information I have, the better my chances of solving the problem. I'll keep an eye out for it.
