### ISSUE TITLE
[BUG] Support for node V16.13.0

### ISSUE THREAD

**Issue by NeuesTwix** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#112]
### Logs
No message in the logs regarding the issue.

### Describe the bug
Since I updated node to v16.13.0 I can't controll my RGB 3 Channel light strip. It just doesn't respond to anything. There is no message in the logs even with debug mode enabled. It doesn't respond on any devide (Mac, iPad, iPhone, HomePod).
When starting homebridge the pluging recognizes the current state of the lights but after turning it on or off in HomeKit it doesn't update it again.
### To Reproduce
1. Update node to v16.13.0
2. Try turning the lights on/off

#### Host Hardware
* Hardware: Raspberry Pi
* OS Version: Raspbian GNU/Linux Stretch (9)

#### Homebridge and MagicHome 
* Homebridge 1.3.6
* Homebridge MagicHome Dynamic Platform version 1.9.4
* Link to the MagicHome Device on the seller's website: https://www.amazon.de/gp/product/B075KKCS5L

**Comment by DrJapan** [comment]
I have the same issue.

**Comment by SkyFire46** [comment]
Hello,
i have the same issue.
In have the log send with.[](url
[homebridge.log.txt](https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/files/7533585/homebridge.log.txt)
)

**Comment by paulocpcorrea** [comment]
Same here... any suggestion?

**Comment by NeuesTwix** [comment]
> Same here... any suggestion?

I downgraded node back to 14.18.0 but now another plugin is making problems. Maybe that’s working for you.
 I hope they bring out an update soon.

**Comment by paulocpcorrea** [comment]
> > Same here... any suggestion?
> 
> I downgraded node back to 14.18.0 but now another plugin is making problems. Maybe that’s working for you. I hope they bring out an update soon.

I can't, because if I downgrade the Soma Smart Shades plugin stops working... sad...

**Comment by bwp91** [comment]
> > > Same here... any suggestion?
> > 
> > 
> > I downgraded node back to 14.18.0 but now another plugin is making problems. Maybe that’s working for you. I hope they bring out an update soon.
> 
> I can't, because if I downgrade the Soma Smart Shades plugin stops working... sad...

Soma plugin should still work with node 14, apart from the warning message about the node version, it shouldn’t actually stop working?

**Comment by PatDal81** [comment]
Update to 1.9.5 - this version fixed this issue for me.  It is now working on the latest version of Node.js (16.13.0)

**Comment by Stan-Dart** [comment]
Update to 1.9.6 works again with Node.js 16.13.0 for me.Thank you.

**Comment by Zacknetic** [comment]
@NeuesTwix , please upgrade back to node 16 and update the plugin to the latest version. Let me know how it goes. Thank you.

**Comment by NeuesTwix** [comment]
> @NeuesTwix , please upgrade back to node 16 and update the plugin to the latest version. Let me know how it goes. Thank you.

Already did. Thank you. It works as perfect as before.

**Comment by Zacknetic** [comment]
Very happy to hear that. Closing this issue now as solved.
