### ISSUE TITLE
[BUG] Causing homebridge service to randomly restart

### ISSUE THREAD

**Issue by etracer65** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#114]
### Logs

[log.txt](https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/files/7541780/log.txt)

### Describe the bug

Random restarts of Homebridge service because of:

```
[15/11/2021, 16:30:44] Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:919:11)
    at Socket.close (dgram.js:741:3)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-magichome-dynamic-platform/src/magichome-interface/Discover.ts:66:16)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

### To Reproduce

Happens sometimes in a loop on boot - multiple times in a row. At end of startup device discovery throws the error and homebridge restarts and then this process repeats multiple times. Then will be stable for a while and then happen again somewhat randomly. Seems to be related to periodic device discovery.

### Expected behavior

Not having homebridge keep restarting.

### Additional context

Only have one Magic home device: https://www.amazon.com/gp/product/B07V7T3ZXV

Also using (but no problems with):
TP-link smart plugs via homebridge-tplink-smarthome v6.4.0
Philips Wiz lightbulbs via @krystofcelba/homebridge-wiz-lan v4.0.1

#### Host Hardware
* Hardware: Raspberry Pi 4 B 4GB
* OS: Homebridge install image
* OS Version: Raspbian GNU/Linux 10 (buster)

#### Homebridge and MagicHome 
* Homebridge / HOOBS version: 1.3.6
* Homebridge MagicHome Dynamic Platform version: 1.9.6
* Node version: v14.17.4
* Link to the MagicHome Device on the seller's website: https://www.amazon.com/gp/product/B07V7T3ZXV

#### Screenshots
N/A

**Comment by etracer65** [comment]
Forgot to mention that I'm also running 3 instances of the Homebridge service. Actual instances - not child bridges. The default instance for the main family, and 2 separate instances to allow the kids to have their own "home" with only access to their devices. That way they can both have a room named "My Room" and do things like "Turn on my lights" in Homekit. Not sure if this is causing a conflict. Don't have any problems with other plugins.

**Comment by etracer65** [comment]
Some more info: Just saw this in the log of one of the other instances:

```
(node:3794) UnhandledPromiseRejectionWarning: Error: bind EADDRINUSE 0.0.0.0:48899
    at dgram.js:357:20
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3794) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3794) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[15/11/2021, 17:06:27] Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:919:11)
    at Socket.close (dgram.js:741:3)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-magichome-dynamic-platform/src/magichome-interface/Discover.ts:66:16)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

**Comment by Zacknetic** [comment]
> Forgot to mention that I'm also running 3 instances of the Homebridge service. Actual instances - not child bridges. The default instance for the main family, and 2 separate instances to allow the kids to have their own "home" with only access to their devices. That way they can both have a room named "My Room" and do things like "Turn on my lights" in Homekit. Not sure if this is causing a conflict. Don't have any problems with other plugins.

Hi, I can't attest to other plugins or their functionality compared to mine. But yes, the fact that other plugins are running while mine isn't is a good indicator that it is the root cause.

I have never tried running multiple Homebridge instances on a single device before. Here are some assumptions based on what you've told me. Please correct me if I am wrong.

- You have Homebridge instances A, B, and C each running independently on separate ports on the same Pi
- Instance A has Magichome plugin 1.9.6 installed and configured
- Instances B and C do not have MagicHome plugin installed, nor have they ever

I am not a network expert, however EADDRINUSE error usually means that somehow a network call was made twice on the same port before being closed.

I think one of four things are happening:

1. The Magichome plugin is running on more than one instance at a time or is somehow being called more than once due to multiple instances
2. Somehow another plugin is interfering with the Magichome plugin
3. Somehow the port isn't being properly closed during the discovery loop. Haven't seen this reported by other users. Perhaps a weird async call that never resolves... 
D. Gremlins

Here is some homework:

- When did this issue first start happening?
- Could you please upgrade to the latest version of Homebridge and node 16.x?
- Could you please tell me what happens when you temporarily disable instances B and C from auto starting, restart the pi, and only let A run?

**Comment by etracer65** [comment]
Some feedback:

 > I have never tried running multiple Homebridge instances on a single device before. Here are some assumptions based on what you've told me. Please correct me if I am wrong.
>
> You have Homebridge instances A, B, and C each running independently on separate ports on the same Pi
> Instance A has Magichome plugin 1.9.6 installed and configured
> Instances B and C do not have MagicHome plugin installed, nor have they ever

Yes, multiple named instances running on separate ports. Like:
`hb-service install --user homebridge --service-name homebridge-two --port 8080`

The installed plugins are available to all instances and there's no way I know of to only have them installed in one. Using the guy to install plugins makes them available in all instances. Each has it's own plugin config though. And in my case I want them to work in all the instances anyway.

> When did this issue first start happening?
> Could you please upgrade to the latest version of Homebridge and node 16.x?
> Could you please tell me what happens when you temporarily disable instances B and C from auto starting, restart the pi, and only let A run?

Just installed the MagicHome plugin today. Was running fine before this.

Already running the latest Homebridge (1.3.6). Can try upgrading node later but concerned about some compatibility problem reports in some of the other plugins I'm using.

I'll try disabling the other instances and see what happens - but can't do this until tomorrow. The problem is somewhat random where it will be a burst of problems then a long gap of no problems so might not be very definitive as I can't leave the instances disabled for a long period. The big problem is that the random restarts of the homebridge services are causing havoc with my automations.

**Comment by Zacknetic** [comment]
Okay, so more than one instance is using the MagicHome plugin simultaneously? There is more than one instance that includes MagicHome configurations in its own config.json?

**Comment by etracer65** [comment]
> Okay, so more than one instance is using the MagicHome plugin simultaneously? There is more than one instance that includes MagicHome configurations in its own config.json?

This is correct. I suspect that the problem is that you simply need to handle the exception of the bind to port 48899 might fail because of a conflict with another plugin instance. The reason it's probably worse at boot is that all the instances start together. Then they're discovery timing spreads out and they collide less often.

**Comment by Zacknetic** [comment]
Okay, that makes everything clear. Yes, my plugin does not support multiple instances running at the same time.

Even if I wrote a feature to disable the periodic discovery function, booting up all 3 instances at the same time would still be a gamble.

Regardless, I will add disabling period discovery to the roadmap though I cannot give a time range as to when it will release. Once that happens you could probably solve this issue by staggering your HomeBridge bootups. Even now, you may be able to solve this issue by doing so. The discovery takes about 5 seconds and loops every 30 seconds. Perhaps staggering your instance startups by 10s each could do the trick.

The most stable experience will be to remove the configuration for MagicHome on the other two instances. I was trying to think of your use case for this. The only one I can think of is that you use the blacklist feature to prevent certain lights from showing up on certain bridges. Is this so?

Let me know if you plan on trying these solutions, if so, please share the results. 

Eventually, I will mark this as 'wont-fix' as this use case is outside the intended scope of the program.

**Comment by etracer65** [comment]
> The most stable experience will be to remove the configuration for MagicHome on the other two instances. I was trying to think of your use case for this. The only one I can think of is that you use the blacklist feature to prevent certain lights from showing up on certain bridges. Is this so?

Yes, exactly. The led strip is in one of the kids bedrooms so their instance has it whitelisted and the other kid's instance has it blacklisted. So they can each have a "My Room" that has only the accessories applicable.

I think simply handling the exception and not faulting homebridge would be enough for me. Alternately a setting to disable discovery would be useful. After the initial setup I can rely on the cached accessories (they have static IP's via DHCP reservations).

I'll look into staggering the starts but that's only a workaround as they're likely to collide again some point later.

I am a developer (work on the Betaflight project), but primarily in C and haven't played with TypeScript any. But maybe I'll take a look at it if I get some time.

**Comment by etracer65** [comment]
So I tried offsetting the start of the separate instances by 10 seconds each. Helps with the initial boot since they don't all immediately collide, but within an hour or so the timing drifts and they start colliding and faulting the homebridge service again.

**Comment by Zacknetic** [comment]
Hi, new update 1.9.7. I have done three things

1. Rechecked the try catch logic so if an error occurs, it doesn't crash Homebridge
2. Added an option to disable periodic discovery (plugin settings> scroll all the way down > "periodic discovery"
3. Perhaps removed the issue entirely by opening the port in shared mode.

So. Please do me a favor and de-stagger your instance startups. Update MH to 1.9.7 and try them all at once. If they don't fail, great. If they do. Disable periodic discovery, re-stagger your instance startups, and you should be good to go.

Let me know how it goes.
-z

**Comment by etracer65** [comment]
Thanks for the quick update! Just updated and so far results are positive. Started all instances at the same time (with discovery still enabled) and no conflicts or crashes in the homebridge service. I'll report back after giving it a day to run.

Thanks again for the support.

**Comment by Zacknetic** [comment]
Sounds good. Let me know.

**Comment by etracer65** [comment]
Good news! I've had the plugin running in multiple instances for a full day now and no more homebridge service crashes. I think using shared mode for the port probably resolved the problem as I'm not seeing any errors or warnings. However handing the port open failure possibility was probably good in the long term. Thanks again for looking into this and fixing it so quickly. I'm going to close this as the issues are fully resolved.
