### ISSUE TITLE
[BUG] Discovery not working

### ISSUE THREAD

**Issue by jhays** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#118]
### Logs
[homebridge-magichome-log.txt](https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/files/7921217/homebridge-magichome-log.txt)

### Describe the bug
Plugin is not discovering any magic home LED lights on my network.

I am able to use/control my lights from the magic home app, or from a raspberry pi running different homebridge magic home plugin. I've since disabled that, and I'm moving to homebridge on an ubuntu machine. I've installed this plugin, but it seems to be unable to discover any of my lights, so it never shows any devices in homekit. 

### To Reproduce
Install this plugin
Restart homebridge
Watch logs and observe that discovery never finds any devices. 

### Expected behavior
Discovery should find devices and then surface controls for them in homekit. 

### Additional context
With a different magichome plugin where the config has explicit entries for each light via IP or MAC, I am able to control the devices. So I am confident that the devices should be accessible on my local network. 

#### Host Hardware
* Hardware: Intel NUC
* OS: Ubuntu
* OS Version: 20.04

#### Homebridge and MagicHome 
* Homebridge / HOOBS version 1.4.0
* Homebridge MagicHome Dynamic Platform version 1.9.7
* Link to the MagicHome Device on the seller's website:
https://www.amazon.com/LEDENET-Smart-Controller-Channels-Control/dp/B01DY56N8U/

**Comment by jhays** [comment]
Went to discord for further support.
After it was recommended that I try the beta version, and set a subnet of 255.255.255.255 (a new setting enabled by the beta version), that still didn't resolve my discovery issues. 
However, i happened to try setting the actual IP of one of my LED lights in that new subnet field, restarted homebridge, and then that light was discovered. So I added additional subnet options for each of my other LED lights, restarted, and they are now all discovered and working in HomeKit.

**Comment by 5030MS** [comment]
Hi  @jhays , I have the same problem with device: 
https://www.amazon.com/LED-Controller-WIFI-Wireless-Smartphone/dp/B0746654D5/ref=sr_1_8?crid=30SS8WI5HCL7F&keywords=magic%2Bhome%2Brgbw%2Bwifi%2Bcontroller&qid=1659864298&sprefix=magichome%2BRGBW%2Caps%2C172&sr=8-8&th=1
My Homebridge version 1.5.0
Homebridge MagicHome Dynamic Platform version 1.9.7
I am begginer with homebridge. Please, could you tell me your steps in details? Where I can set a subnet for beta version?
