### ISSUE TITLE
Feature-Request: Homebridge Verification

### ISSUE THREAD

**Issue by iRayanKhan** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#14]
Hello,

It would be great if this plugin could enroll in the [Homebridge Verification program](https://github.com/homebridge/verified).

**Comment by Zacknetic** [comment]
Hey, actually it is enrolled. Need to push some changes including some bugfixes and an updated config.json. I'll close this when we are successfully verified. Thank you for your enthusiasm!

**Comment by Zacknetic** [comment]
All set. We're verified!

**Comment by iRayanKhan** [comment]
Woohoo!
