### ISSUE TITLE
Does this plugin with work a single color controller?  I have a Sumaote SUUSWD413

### ISSUE THREAD

**Issue by ginnjuicewv** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#18]
Hi, having a hard time getting this plugin to work with a Sumaote SUUSWD413, Amazon link:

https://www.amazon.com/gp/product/B07JC3L4Z6/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

Is this plugin compatible, and if so, how do I get it working?

Thanks

**Comment by Zacknetic** [comment]
Hey there, we can probably get it working as it uses the magichome app. 

Could you please upload your homebridge.log and config.json files? Try to drag and drop the actual files instead of copying and pasting the text as it could be quite long. 

Thank you. :)

**Comment by ginnjuicewv** [comment]
Thank you, please see attached.  I've tried to clean up the files to avoid anything personally identifiable, hopefully didn't clean out too much.  New @ Homebridge (Hoobs), first time uploading logs & configs.
[Archive.zip](https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/files/5059490/Archive.zip)

**Comment by Zacknetic** [comment]
Ah, that's why. Hoobs doesn't play nice with my plugin. Going to merge this issue with another concerning the same bug. Hang tight.

**Comment by Zacknetic** [comment]
Hoobs does not play nice with my plugin. Considered merging this with another issue, however this may have further bugs down the line seeing it is a new controller.  I will attempt to find a solution I saw on another magichome plugin. Hang tight.

**Comment by ginnjuicewv** [comment]
I somehow found Hoobs before I found Homebridge, is the only reason I went with it.  Just put Homebridge on a different SD card, and your plugin found my controller.  Going to stick with Homebridge for now, but I'll be happy to test on Hoobs if you figure out a solution.

Thanks!

**Comment by Zacknetic** [comment]
Thank you, I will let you know if this is necessary. Closing this for now.
