### ISSUE TITLE
Plugin startup crashes Homebridge

### ISSUE THREAD

**Issue by iRayanKhan** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#21]
## Environment:
* Raspberry Pi 3B (Using homebridge image)
* Node: ```v12.18.2```
* NPM : ```6.14.7```
* Homebridge: ```1.1.2```

## Issue:
I am attempting to hookup 6 lightstrip controllers with this plugin, but homebridge returns the following, and crashes:
(Sorry, it won't let me copy and paste from my phone D:)
![image](https://user-images.githubusercontent.com/34495712/91216650-eefce980-e6db-11ea-88d6-c3b8c18d6544.png)

## Config:
```
{
    "bridge": {
        "name": "Homebridge 74C0",
        "username": "0E:D5:9C:65:74:C0",
        "port": 51618,
        "pin": "726-16-707"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "pruning": {
                "pruneMissingCachedAccessories": false,
                "restartsBeforeMissingAccessoriesPruned": 3,
                "pruneAllAccessoriesNextRestart": false
            },
            "whiteEffects": {
                "simultaniousDevicesColorWhite": true,
                "colorWhiteThreshold": 10,
                "colorWhiteThresholdSimultaniousDevices": 50,
                "colorOffThresholdSimultaniousDevices": 5
            },
            "deviceManagement": {
                "blacklistOrWhitelist": "blacklist",
                "blacklistedUniqueIDs": [
                    ""
                ]
            },
            "platform": "homebridge-magichome-dynamic-platform"
        }
    ]
}
```

## Troubleshooting:
I have tried:
* Updating the plugin
* Updating config-ui-x
* Clear both persist and cachedAccessories
* Ensure all devices are able to be used in local mode

![image](https://user-images.githubusercontent.com/34495712/91216691-fe7c3280-e6db-11ea-84a7-8b3a5d157d35.png)

**Comment by Zacknetic** [comment]
Yes... your "phone".

**Comment by iRayanKhan** [comment]
> Yes... your "phone". 

Do you mean the screenshots? It's a shortcut lol. I saw an earlier issue about different controller protocols like V2,4, etc. is that the cause of it?

**Comment by LoganDan** [comment]
Hey @iRayanKhan, not sure I have anything to add. Just want to say I'm experiencing this issue as well. I'm going to look at any recent changes and see if they might have caused this.

**Comment by Zacknetic** [comment]
@iRayanKhan wow sorry to leave you hanging with just that reply. Somehow my message didn't get finished. I think I was doing some more research into the issue midway to an actual reply and got sidetracked. I did want to thank you for all that information and the most unique log I've ever received. Appreciate the effort. 

Installed my plugin on a new pi and got the same errors as you on first few startups. But it eventually started working smoothly.

Classes started today so I won't get a chance to look at this til the weekend. 

@LoganDan The issue is in transport.ts. I do some hacky stuff there to get V9 firmware bulbs to work properly. There are also many warnings in the diff, but I am unclear what they are. Version management is not my strong suit. Any help is appreciated.

**Comment by Zacknetic** [comment]
Hey, @LoganDan and @iRayanKhan

So I found a bug that was causing the plugin to not wait long enough for the light to reply with a version type. Even worse, it gave a false version type if it got no response. I've updated the plugin to handle this better so if you'd like, give this another try.

Please update in config ui x > plugins > homebridge-magichome-dynamic-platform > update. (!Important!) Next purge all magic-home accessories by going to config ui x > plugins > homebridge-magichome-dynamic-platform > settings > checkmark "Prune All Accessories Next Restart (Warning Dangerous!)" > restart homebridge at least twice > un-checkmark "Prune All Accessories Next Restart (Warning Dangerous!)" > restart homebridge.

Let me know how this goes.

**Comment by vpiskunov** [comment]
@Zacknetic thanks for your effort! Still same issue for me though, fresh install & no update available as currently on v1.4.3 - is there any more potential issues that could trigger this? Once the plugin is added/installed my homebridge just keeps crashing every few seconds. Never manages to properly keep running. Any ideas would be great help!

**Comment by Zacknetic** [comment]
@vpiskunov I'd ask for your logs but I think I know what's going on. There are some incompatibilities with the old plugin so if you have magichome accessories associated with the old plugin, they mess things up. Follow these steps:

1. This is important! Purge all magic-home accessories by going to config ui x > plugins > homebridge-magichome-dynamic-platform > settings > checkmark "Prune All Accessories Next Restart (Warning Dangerous!)" > restart homebridge at least twice 
2. Lastly un-checkmark "Prune All Accessories Next Restart (Warning Dangerous!)" > restart homebridge.

**Comment by vpiskunov** [comment]
@Zacknetic here's my log anyway (sorry it's a full one, just look for any ECONNRESET) 

https://gist.github.com/vpiskunov/32be0c09854e31019a9a8bfd606d6542

I've done all steps word by word, any have a clean install of homebridge with this being the only plugin ever ;) but last step, to un-checkmark I didn't do. Wouldn't expect that to mess it up, as it's a shutdown-time-flag?

**Comment by vpiskunov** [comment]
Any ideas @Zacknetic? if there's an idea to a fix/pointer I could try getting a PR in. Though I've not explored the repo much yet!

**Comment by Zacknetic** [comment]
@vpiskunov to be honest you shouldn't need to use a clean install of homebridge. Be sure to purge the accessories the way I explained. What it does is completely remove the magichome accessories. But it will do so every restart if it's not disabled.

Checkmark "prune All Accessories Next Restart " > save> restart
Uncheckmark "prune All Accessories Next Restart " > save > restart

Just to be sure. Because the accessories don't necessarily remove themselves even after a clean homebridge install.

**Comment by Zacknetic** [comment]
Looking further. That probably won't solve your problem. Could you please send me a link to your controller wherever you bought it? A picture would help. 

Is it RGB, RGBW, RGBWW? Is it a strip or a bulb?

I think the wrong protocol is being sent.

**Comment by vpiskunov** [comment]
Sure - I meant that it's an initial install, which happened after your latest version rollout with the changes above. Just to say I never had it work since the 1st attempt. 

The controller is this one: https://www.amazon.co.uk/gp/product/B07KVWT38V

**Comment by Zacknetic** [comment]
It will definitely work in the magichome app. There are variations to the protocol, that's what may be causing the issue. 

A few things;

- Any chance you could connect your homebridge server to the same 2.4ghz band as your magichome lights? I see it's connected VIA ethernet

- Could you please enable debugging, disable "prune all accessories", run homebridge a few more times and then send me an updated log?

- I'm kind of at a loss right now as to why it's not working, but we'll push on.

**Comment by johncameron3** [comment]
I'm having similar issues... any update on this? (first time user of this plugin and 'magic home' lights)

Error:

```
[9/21/2020, 7:57:12 PM] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
[9/21/2020, 7:57:12 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by Zacknetic** [comment]
@johncameron3 No there is no update so far. 

Please keep in mind I'm one person maintaining the code for this plugin in my spare time. I do what I can but school / work comes first. 

I think the firmware on the GRB devices may have updated the protocol to 9bytes instead of 8. I'm worried if I change this, it will break this plugin for users without the updated firmware version. 

I will try it regardless because this may or may not be problem, but it'd be good to confirm.

**Comment by vpiskunov** [comment]
@Zacknetic appreciate you looking into this & know you’re busy! If it’s a small change for the 9bytes, let me know what to do, and I can apply the change locally in my install, and report on results. 

Otherwise perhaps one way would be to make a feature-branch and we could install it thru NPM via git/https clone link to that branch?

**Comment by johncameron3** [comment]
Anything I can do to help / test?

**Comment by Zacknetic** [comment]
@vpiskunov @johncameron3 @LoganDan @iRayanKhan  Making the necessary changes now to the development branch. Standby.

**Comment by vpiskunov** [comment]
Great @Zacknetic thank you! I have ordered a few more of these devices so I will be able to test them all. Any way I should pull in the dev branch into homebridge? Git URL in npm?

**Comment by Zacknetic** [comment]
I have updated the master branch. Be sure to purge ALL your magichome accessories either by deleting the accessories folder or using my prune feature. Be sure to turn the prune feature off after you restart.

**Comment by jocamero** [comment]
Updated plugin. Pruned accessories. Still crashing.

**Comment by Zacknetic** [comment]
Okay then I will revert back and consider my options. Thanks for letting me know.

**Comment by Zacknetic** [comment]
@jocamero @vpiskunov @LoganDan @iRayanKhan 

I have come up with a new version of the plugin that should solve this issue.

Please update your plugin to version 1.5.1 . Note: if you are updating from version 1.4.x you'll need to purge all your magichome devices after updating. Then restart homebridge to rescan.

With help, I found a bug in the code that caused duplicate device to register if the user had multiple subnets. Thus the crash. I was trying to scan on more than one subnet but didn't account for devices showing up on more than one.

Let me know how it goes. Thank you.

**Comment by iRayanKhan** [comment]
Just tested it today @Zacknetic, I get this error crashing home bridge on boot:

```
[11/3/2020, 11:41:23] [homebridge-magichome-dynamic-platform] ( Modified) Light version: 1 matches known device type records
[11/3/2020, 11:41:23] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
[11/3/2020, 11:41:23] [homebridge-magichome-dynamic-platform] 
Registering new accessory 'Simple GRB' 
Model: 'AK001-ZJ2131' 
Unique ID: 'C82E47604325' 
IP-Address: '192.168.4.208' 
Light Version 8 
Version Modifier: 51
Protocol Version: 1

[11/3/2020, 11:41:23] [homebridge-magichome-dynamic-platform] 
Registered 7 Magichome device(s). 
New devices: 4 
Cached devices that were seen this restart: 3 
Cached devices that were not seen this restart: 0

[11/3/2020, 11:41:23] Got SIGTERM, shutting down Homebridge...
[11/3/2020, 11:41:23] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
[11/3/2020, 11:41:23] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
```

**Comment by Zacknetic** [comment]
@jocamero @vpiskunov @LoganDan @iRayanKhan 
 Please update to version 1.6.2, purge your magichome devices using the built in settings "prune all accessories next restart". Be sure to disable that setting after everything is successfully purged. 

I'm fairly confident about this update, but you never know. If things don't work, be sure to upload a sanitized homebridge.log file. 

Additionally, you can contact me and other magichome plugin users here at the [official MagicHome Discord Server.](https://discord.gg/c8xpmZSNZC) I am usually much more responsive there.

**Comment by iRayanKhan** [comment]
1.7.4 fixed it for me. Thank you @Zacknetic!

**Comment by Zacknetic** [comment]
Thank you god.
