### ISSUE TITLE
One color dimmer

### ISSUE THREAD

**Issue by Supermarco333** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#23]
Hello,

First of all, a huge thanks to the developers for maintaining this plugin.

I am using a monochromatic MagicHome dimmer to control my white LED on my terrasse (https://templates.blakadder.com/assets/images/magichome_single_color.jpg). The MagicHome app recognize the device correctly as I can only adjust between white and black. This is not the case in HomKit, it detects a RGBWW device.

What settings should I modify ?

**Here is the log:**
[9/2/2020, 10:08:48 PM] [homebridge-magichome-dynamic-platform] 
Discovered 1 devices.

HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
[9/2/2020, 10:08:48 PM] [homebridge-magichome-dynamic-platform] 
Registering new accessory 'RGBWW Simultanious' 
Model: 'AK001-ZJ2104' 
Unique ID: '2CF432F5496E' 
IP-Address: '10.0.0.31' 
Version 2 
Version Modifier: 65

[9/2/2020, 10:08:48 PM] [homebridge-magichome-dynamic-platform] 
Registered 1 Magichome device(s). 
New devices: 1 
Cached devices that were seen this restart: 0 
Cached devices that were not seen this restart: 0

**Here is the config:**
{
            "pruning": {
                "pruneMissingCachedAccessories": false,
                "restartsBeforeMissingAccessoriesPruned": 3,
                "pruneAllAccessoriesNextRestart": false
            },
            "whiteEffects": {
                "simultaniousDevicesColorWhite": true,
                "colorWhiteThreshold": 10,
                "colorWhiteThresholdSimultaniousDevices": 50,
                "colorOffThresholdSimultaniousDevices": 5
            },
            "deviceManagement": {
                "blacklistOrWhitelist": "blacklist",
                "blacklistedUniqueIDs": [
                    ""
                ]
            },
            "platform": "homebridge-magichome-dynamic-platform"
        }

**Comment by kevinjohncutler** [comment]
That’s odd, based in the picture it looks identical to the one that Zacknetic worked with me to get running. The plugin worked flawlessly for me.

**Comment by Supermarco333** [comment]
I can control the device (the brightness) but I also have the possibility to adjust the color which doesn't make any sense.

**Comment by Supermarco333** [comment]
I worked a bit on the problem by reading the code. If I have well understood the code, I saw that there's a solution which is already implemented. My device should be detected with "Version Modifier: 33" and use the DimmerStrip config. @Zacknetic Do you have a solution to override the "Version Modifier: 65" ?

**Comment by Supermarco333** [comment]
I think we could do that fix. (@Zacknetic)

    }	else if (lightVersionModifier === 33 **|| lightVersionModifier === 65**){
      lightVersion = 99;
    }

at line 427 in /src/platforms.ts

**Comment by Zacknetic** [comment]
Thank you very much, I think a few bugs were introduced in the latest update and I really appreciate the extra pair of eyes. 

My semester has just started which is why I have been less responsive, however I will make that fix tonight and devote my Monday to bugchecking the code.

On that note, I am looking for someone with some programming experience refactor the code with me. If anything thinks they'd like to partner up please let me know.

Thank you everyone for your patience.

**Comment by Supermarco333** [comment]
I will let you check that I did not suggest something wrong. You have my first comment with all the information. (log+model)

I am able to read and propose some modifications but I absolutely can't develop, I don't know JS. Furthermore, as I am a student, I don't much time either.

Thank you very much for your work.

**Comment by Zacknetic** [comment]
@Supermarco333 Thanks for your patience.

 I've updated the code to be a bit more clean to help with version type issues. Additionally I've added a check for your controller type.

 Please update in config ui x > plugins > homebridge-magichome-dynamic-platform > update. (!Important!) Next purge all magic-home accessories by going to config ui x > plugins > homebridge-magichome-dynamic-platform > settings > checkmark "Prune All Accessories Next Restart (Warning Dangerous!)" > restart homebridge at least twice > un-checkmark "Prune All Accessories Next Restart (Warning Dangerous!)" > restart homebridge.

Thank you.

**Comment by Supermarco333** [comment]
The code is much much lighter. Really good job !

I will try the check when I'll have a bit more time. Thank you for your help.
PS: I have ordered another one color Magic Home, I'll let you know if I have another unknown version modifier. :)

**Comment by Supermarco333** [comment]
It works like a charm ! Perfect and thanks for your help.
