### ISSUE TITLE
Homebridge freezes when restarting after installing.

### ISSUE THREAD

**Issue by AonDor** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#28]
Hi,

I'm relatively new to both Homebridge and this plugin.

I installed the npm, but when I tried to restart Homebridge as directed it freezes in the loading screen and does not load. This does not happen with any other packages. Do you know what the issue could be?

**Comment by Zacknetic** [comment]
Hi, just to be clear here. This problem occurs when this plugin "homebridge-magicome-dynamic-platform" is installed?

May you please upload your homebridge.log by uploading the file. Thank you.

**Comment by Zacknetic** [comment]
I am closing this issue, but feel free to re-open it again if you need additional help.
