### ISSUE TITLE
Homebridge restart

### ISSUE THREAD

**Issue by gerjaneikens** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#30]
i fresh installed a new pi with homebridge for a led controller but i'm getting the warning:
[homebridge-magichome-dynamic-platform] Warning. Was unable to determine state for device:
and after the warning i'll get the error:

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)

and then homebridge is rebooting.

i'm using v1.4.5

config:
![config](https://user-images.githubusercontent.com/9828446/94430567-6cf95800-0194-11eb-83d7-2a3e07920c35.PNG)
log:
![image](https://user-images.githubusercontent.com/9828446/94430669-92866180-0194-11eb-8322-01c46f4c22a7.png)

**Comment by Zacknetic** [comment]
Thank you for this detailed log. Could you please send me a link to the exact device you purchased? I may need to change the way the program logs the light versions and have you retry from there. But first I'll take a look at that device.
-Z

**Comment by gerjaneikens** [comment]
It looks like it happen if i change the name on my iPhone.
https://a.aliexpress.com/_BUuuzB
The RGBW version



Op 28 sep. 2020 om 22:05 heeft Zacknetic <notifications@github.com> het volgende geschreven:

﻿

Thank you for this detailed log. Could you please send me a link to the exact device you purchased? I may need to change the way the program logs the light versions and have you retry from there. But first I'll take a look at that device.
-Z

**Comment by jeremyosterhoudt** [comment]
I'm running into a similar issue, I don't get the warning gerjaneikens gets, however it looks like might be the same device (bought from [Amazon](https://www.amazon.com/Goldwin-Controller-changing-wireless-Compatible/dp/B073Y4BGXG/ref=sr_1_1?dchild=1&keywords=Goldwin&qid=1601695234&sr=8-1)).

Here is the log:

> 10/2/2020, 7:59:02 PM HOOBS listening on port 80.
10/2/2020, 7:59:05 PM Loaded plugin "homebridge-magichome-dynamic-platform".
10/2/2020, 7:59:05 PM Bridge is running on port 51826.
10/2/2020, 7:59:05 PM [homebridge-magichome-dynamic-platform] Scanning broadcast-address: '192.248.44.255' on interface: 'wlan0' for Magichome lights... 
10/2/2020, 7:59:08 PM [homebridge-magichome-dynamic-platform] 
Discovered 1 devices.
10/2/2020, 7:59:08 PM [homebridge-magichome-dynamic-platform] 
Registering cached accessory 'RGBW Simultanious' 
Model: 'AK001-ZJ2134' 
Unique ID: 'C82E475E36A3' 
IP-Address: '192.248.44.96' 
Version 10 
Version Modifier: 6
10/2/2020, 7:59:08 PM [homebridge-magichome-dynamic-platform] 
Registered 1 Magichome device(s). 
New devices: 0 
Cached devices that were seen this restart: 1 
Cached devices that were not seen this restart: 0
10/2/2020, 7:59:09 PM Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
10/2/2020, 7:59:09 PM Got SIGTERM, shutting down Bridge...

Please let me know if there is anything I can do to help.  I'll see if I can capture a network log from the Magic Home app, the device works correctly from the App.

**Comment by Zacknetic** [comment]
Hello, thank you for waiting patiently. The plugin is the issue 99% of the time. The other 1% of the time the issue stems from unusual network setups.

Please update your plugin to version 1.5.1 . Note: if you are updating from version 1.4.x you'll need to purge all your magichome devices first.

With help, I found a bug in the code that caused duplicate device to register if the user had multiple subnets. Thus the crash. I was trying to scan on more than one subnet but didn't account for devices showing up on more than one.

Let me know how it goes. Thank you.

**Comment by Zacknetic** [comment]
Closing this issue for now. Please reopen if the problem persists. Thank you.
