### ISSUE TITLE
Duplicate device

### ISSUE THREAD

**Issue by edmarts** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#31]
Hello, I'm using homebridge and node-red to control my devices and the magichome plugin is duplicating some devices.

It does not take the name of the device, it takes the type of controller and with that it replicates the name.

I already changed the name on the homebridge but even so, when using the device on node-red it keeps the same name.

When I create a node using a device (third one), after save it always takes the second one (that have the same name) in the list according to the attached image.
![erro](https://user-images.githubusercontent.com/2656908/94443405-85a94400-017b-11eb-8989-4ff623045034.png)

How can I define which device is which somewhere?

**Comment by Zacknetic** [comment]
Hello,

I'm not entirely clear what your are asking. My plugin initially auto assigns a name to the accessory in HomeKit. This can be changed in HomeKit by long clicking the device > clicking the gear symbol > and editing the name.

As for nodered, I am unclear what you are attempting to do there. I can offer my input but unless my plugin is malfunctioning in HomeKit, I won't be providing any bugfixes for a different program.

Let me know in a little more detail what you are doing with node red, not just the problem, and I will try to help.

-Z

**Comment by edmarts** [comment]
In the homekit I named the devices correctly and each one lights up normally.

In the homebridge, I also named the devices correctly and there they are also ok.

In the node-red the problem is. There the devices do not change the name. They are displayed with the name that it is discovered in the MagicHome plug-in. So when I select a device (just like the image I sent) it always uses only the first one in the list and not the device I select (the second in the list).

![94443405-85a94400-017b-11eb-8989-4ff623045034](https://user-images.githubusercontent.com/2656908/94472103-9fa94d80-01a0-11eb-9a94-87437fbb61d4.png)

At the terminal, node-red gives a warning that the device is duplicated. (duplicate uniqueID and duplicate device name)

**Comment by Zacknetic** [comment]
Interesting. First and foremost this plugin does not support node-red so I
will not be making any changes regarding this issue as you've stated it is
working as intended in homekit.

It may shed light on a small duplicate problem? I'm not sure, but I will
look over my code for bugs. Thank you.

Please let me know if this issue appears in homekit.

Thank you.
