### ISSUE TITLE
Plugin causes homebridge proccess to end. 

### ISSUE THREAD

**Issue by Tornadoalley** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#34]
Toggling prune accessories does not resolve the issue.

Homebridge Log:

[10/25/2020, 10:40:45 AM] [homebridge-magichome-dynamic-platform] ( Modified) Light version: 1 matches known device type records
[10/25/2020, 10:40:45 AM] Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
[10/25/2020, 10:40:45 AM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[10/25/2020, 10:40:50 AM] [HB Supervisor] Restarting Homebridge...
[10/25/2020, 10:40:50 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[10/25/2020, 10:40:50 AM] [HB Supervisor] Started Homebridge v1.1.6 with PID: 20884

**Comment by Zacknetic** [comment]
Can you confirm that you toggled "prune all accessories next restart" and not "prune all missing accessories"?

**Comment by Tornadoalley** [comment]
Yes, I did that. It seems only v1.4.0 works for me.

**Comment by Zacknetic** [comment]
This seems to be a common issue, I will post back once I have a fix.

**Comment by Tornadoalley** [comment]
Thanks!

**Comment by Zacknetic** [comment]
@Tornadoalley 
Please update your plugin to version 1.5.1 . Note: if you are updating from version 1.4.x you'll need to purge all your magichome devices first.

With help, I found a bug in the code that caused duplicate device to register if the user had multiple subnets. Thus the crash. I was trying to scan on more than one subnet but didn't account for devices showing up on more than one.

Let me know how it goes. Thank you.

**Comment by Tornadoalley** [comment]
Thanks! Will let you know!

**Comment by FaceMan4** [comment]
Same Problem here:
Error: read ECONNRESET at TCP

**Comment by Zacknetic** [comment]
@Tornadoalley @FaceMan4 @hoffma0901

Hi, I've just released an update which may solve some issues. Please update to the latest version 1.6.0, purge all magichome devices using the plugin's settings, and restart homebridge. If anything goes wrong, please post back with an uploaded and sanitized log file.

Thank you.

**Comment by Zacknetic** [comment]
@FaceMan4 @Tornadoalley 
Version 1.7.3 has solved this exact issue for another user. Please let me know if it does for you. Thank you!

**Comment by FaceMan4** [comment]
> @FaceMan4 @Tornadoalley
> Version 1.7.3 has solved this exact issue for another user. Please let me know if it does for you. Thank you!

Last update fix the error for me! Thanks a lot 👍

**Comment by Zacknetic** [comment]
@FaceMan4 very happy to hear that. You're welcome.

@Tornadoalley let me know how it goes.

**Comment by Zacknetic** [comment]
@Tornadoalley closing this issue. Please re-open a new issue if your problem has not been solved. Thank you!
