### ISSUE TITLE
Better support for smart plug?

### ISSUE THREAD

**Issue by saiajin** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#36]
Hi I have a magic home smart plug and it cause this plugin to not work unless I whitelist my devices by ID... and then the smart plug shows up as a colored bulb.... can you add support for the smart plug?

**Comment by Zacknetic** [comment]
Hi, I have no knowledge of a smart plug that's magichome based. Can you send me an Amazon link?

**Comment by saiajin** [comment]
I’m trying to find a link it’s been quite a while... it’s a round plug I’ll keep looking

miles@milesreetz.com
773-301-3041

**Comment by saiajin** [comment]
![EA0A31AB-6BDD-4E42-9A2F-2DF8A7345768](https://user-images.githubusercontent.com/71667075/97510135-5552f200-1941-11eb-992c-fa65c1c5fff4.jpeg)
![B7C9D591-6350-4737-AA5C-AD9B033D923A](https://user-images.githubusercontent.com/71667075/97510137-571cb580-1941-11eb-8db1-c09e88a74580.png)

**Comment by Zacknetic** [comment]
Unfortunately that doesn't show me much information I can use.

You can send me a link to the amazon page or I can work with you directly at some point to learn the protocol.

I will work on the issues in the order I receive them to the best of my ability. That may take time.

**Comment by saiajin** [comment]
I found it on AliExpress:

https://m.aliexpress.com/item/4000034580429.html

**Comment by saiajin** [comment]
Here they are on Amazon

Alexa Smart Plugs - Aoycocr Mini WIFI Smart Socket Switch Works With Alexa Echo Google Home, Remote Control Smart Outlet with Timer Function, No Hub Required, ETL/FCC Listed 4 Pack Only 2.4GHz Network https://www.amazon.com/dp/B07N1JPPXK/ref=cm_sw_r_cp_api_i_W1GMFbFGTY4EH

**Comment by saiajin** [comment]
Similar to these:

Smart Plug Compatible with Alexa Google Assistant IFTTT Siri Shortcut, Magic Hue WiFi App Control Timer Schedule Smart Outlet, No Hub Required, FCC Certified Smart WiFi Socket - 4 Pack https://www.amazon.com/dp/B07XNBVVXV/ref=cm_sw_r_cp_api_i_75GMFbGRGHDJ9

**Comment by saiajin** [comment]
I’ll do whatever u need to help!

**Comment by Zacknetic** [comment]
Great. Thanks for the links. I'll have it ordered and create the logic for it when it arrives. Or when I am able to devote time to work with you. Whichever comes first.

Self promotion here. Take a second to take a look at my [GitHub sponsors page](https://github.com/sponsors/Zacknetic) if you have other magic home devices and feel like this plugin helps you.

**Comment by Zacknetic** [comment]
Hi, it looks like the plug will be delayed. Instead, I am ready to work with you directly to get this plug working. Please join the [MagicHome discord channel](https://discord.gg/FqH6n33aUD) and post in the #help channel when you'll be free to schedule an appointment. We can figure out a time to work one-on-one.

**Comment by saiajin** [comment]
All is Well! I now have my 2 color changing bulbs and a new device, a "Power Socket" Working great in Hoobs! Thank you! Fantastic support!
