### ISSUE TITLE
Installed 1.51 and still getting problems

### ISSUE THREAD

**Issue by m0v1em4n** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#37]
First I would like to thank you for your time, but i am still getting issues with 1.51

> [10/30/2020, 8:20:34 AM] [homebridge-magichome-dynamic-platform] 
Registering existing accessory 'Simple GRB' 
Model: 'AK001-ZJ2131' 
Unique ID: 'C82E475FF973' 
IP-Address: '192.168.0.136' 
Light Version 8 
Version Modifier: 51
Protocol Version: 1

[10/30/2020, 8:20:34 AM] [homebridge-magichome-dynamic-platform] 
Registering existing accessory 'RGBW Non-Simultanious' 
Model: 'AK001-ZJ2101' 
Unique ID: '2CF432F4D667' 
IP-Address: '192.168.0.123' 
Light Version 8 
Version Modifier: 51
Protocol Version: 8

[10/30/2020, 8:20:34 AM] [homebridge-magichome-dynamic-platform] 
Warning! Continuing to register cached accessory 'RGBW Non-Simultanious' despite not being seen for 9 restarts. 
Model: 'AK001-ZJ2101' 
Unique ID: '5002913333B1' 
IP-Address: '192.168.0.161'
 Version undefined 
Version Modifier: 51 

[10/30/2020, 8:20:34 AM] [homebridge-magichome-dynamic-platform] 
Warning! Continuing to register cached accessory 'RGBW Non-Simultanious' despite not being seen for 9 restarts. 
Model: 'AK001-ZJ2101' 
Unique ID: '500291331038' 
IP-Address: '192.168.0.140'
 Version undefined 
Version Modifier: 51 

[10/30/2020, 8:20:34 AM] [homebridge-magichome-dynamic-platform] 
Registered 4 Magichome device(s). 
New devices: 0 
Cached devices that were seen this restart: 2 
Cached devices that were not seen this restart: 2

[10/30/2020, 8:20:34 AM] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:208:20)

>

**Comment by Zacknetic** [comment]
There's a number of issues here that I can see. The most obvious is that you have two lights with versions listed as "undefined". That's never good.  Can you confirm that after updating to v1.5.1 you used the "prune all accessories next restart" function in plugins > homebridge-magichome-dynamic-platform > settings?

I also see the second light discovered as "light version 8" (RGBW) but the plugin has set them to protocol version 1 (GRB). That will cause this exact crash. 

Can you please link me the controllers / bulbs that you have. Exactly if you can. It doesn't matter amazon or aliexpress etc... I just need a reference.

Thank you.

**Comment by m0v1em4n** [comment]
Hi,

Yes tried the Prune, but that didn't work, I am using the Magichome wifi controllers and has far has i am aware all my strips are just RGB, will try and find some links for you

**Comment by Zacknetic** [comment]
```
[10/30/2020, 8:20:34 AM] [homebridge-magichome-dynamic-platform]
Warning! Continuing to register cached accessory 'RGBW Non-Simultanious' despite not being seen for 9 restarts.
```

This means that it is registering a cached device. One which has been around for 9 restarts. Please prune the accessories by doing the following:  enable "pruneAllAccessoriesNextRestart" > restart > ensure that accessories were pruned in the log > disable "pruneAllAccessoriesNextRestart" > restart.

There might still be an issue, but this will solve the duplicate problem and that's a start.

**Comment by jzdeb** [comment]
@Zacknetic I'm getting the same problem. I did the steps as above with no help.

```
11/2/2020, 10:40:20 PM [homebridge-magichome-dynamic-platform] 
Discovered 1 devices.
11/2/2020, 10:40:21 PM [homebridge-magichome-dynamic-platform] 
 Platform.ts.createAccessory(): 
Assigning controller to device: UniqueId: 'C82E475FC37D' 
IpAddress '192.168.0.146' 
Model: 'AK001-ZJ2131'
Original Light Version: 8
Light Version Modifier: 51
11/2/2020, 10:40:21 PM [homebridge-magichome-dynamic-platform] ( Modified) Light version: 1 matches known device type records
11/2/2020, 10:40:21 PM Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
11/2/2020, 10:40:21 PM HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
11/2/2020, 10:40:21 PM [homebridge-magichome-dynamic-platform] 
Registering new accessory 'Simple GRB' 
Model: 'AK001-ZJ2131' 
Unique ID: 'C82E475FC37D' 
IP-Address: '192.168.0.146' 
Light Version 8 
Version Modifier: 51
Protocol Version: 1
11/2/2020, 10:40:21 PM [homebridge-magichome-dynamic-platform] 
Registered 1 Magichome device(s). 
New devices: 1 
Cached devices that were seen this restart: 0 
Cached devices that were not seen this restart: 0
11/2/2020, 10:40:21 PM Got SIGTERM, shutting down Bridge...
11/2/2020, 10:40:21 PM Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
11/2/2020, 10:40:21 PM Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
```

This is the item I purchased: [Outdoor LED Strip](https://www.amazon.ca/gp/product/B0814PMDSP/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1)

**Comment by Zacknetic** [comment]
@jzdeb separating the threads as these are different issues

**Comment by Zacknetic** [comment]
@m0v1em4n closing this issue for the time being, feel free to re-open with an uploaded log file if the problem persists. Thank you.
