### ISSUE TITLE
Plugin issue on v1.6.3

### ISSUE THREAD

**Issue by edmarts** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#42]
Hi! After upgrading to v1.6.3, he duplicated the devices. The old ones remained in the homebridge with the names created before but they no longer work and created new ones with the generic names (see image)

And the following message appears in the log:
HAP Warning: Characteristic 00000008-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000049-0000-1000-8000-0026BB765291. Adding anyway.

![names](https://user-images.githubusercontent.com/2656908/98935558-76c7e800-24c2-11eb-9f01-0e96282ec790.png)

**Comment by edmarts** [comment]
And this issue returns :(

https://github.com/NorthernMan54/node-red-contrib-homebridge-automation/issues/66

**Comment by or-agami** [comment]
Please see my closed [issue](https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/issues/41)
Long story short; try to prune all devices > restart > turn it back off, that worked in my case

**Comment by edmarts** [comment]
But won't that mess up other devices from other plugins?

**Comment by edmarts** [comment]
I remove only the led strips and they come back to normal... thanks!!!

**Comment by or-agami** [comment]
If you do this within the plugin setting it will prune only the plugin's accessories.
nice to hear that it works for you, you may want to close the issue :)
