### ISSUE TITLE
Dont set color and brightness on automations / scenes

### ISSUE THREAD

**Issue by edmarts** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#43]
Hello. I'm creating some automations and scenes in shortcut to change the color of the led according to some status of sensors but it doesn't do it.

I created a test scene just to turn on a ed with 100% red and another to turn on a led with 100% green ... it just turns on the led with the last color that I turn on and with only 30% brightness.

This only happens with scenes (homekit app, shortcut app and Eve app). In the homekit app whan I turn on pressing the button and select color it's ok and when I ask to Siri it's ok too.

See the picture... I create a green scene but its show other color:
![1](https://user-images.githubusercontent.com/2656908/99261834-fd9afe80-27fb-11eb-9f0e-c09c686ce347.jpg)
![2](https://user-images.githubusercontent.com/2656908/99261851-025fb280-27fc-11eb-8ec6-339753013b55.jpg)

**Comment by Zacknetic** [comment]
Hello, thank you for bringing this to my attention.

This is a bug I thought I had squashed a few updates ago. Let me get up to speed:
What version of Homebridge MagicHome Dynamic Platform are you using?
May you please upload a homebridge.log or log.txt file? (please no images of logs).
Does restarting Homebridge solve the issue?

By the way, that is a very nice looking dropped ceiling. I love it! When I lived in Chengdu my apartment was designed that way too, it looks fantastic.

**Comment by edmarts** [comment]
I'm using homebridge-magichome-dynamic-platform v1.7.4
I tried restart homebridge but the same issue continues.

Thanks for the compliment, I love too the dropped ceiling!! :)

**Comment by Zacknetic** [comment]
Would you mind joining the [Magic Home Discord Channel](https://discord.gg/FU6Nzan5) I'd like to work with you one-on-one if possible.

**Comment by edmarts** [comment]
Hi!! Some news? I joined discord channel but I didn't see anything there about the issue

**Comment by Zacknetic** [comment]
Hey there, discord is a chat platform so there's not going to be any news about your specific issue. 

Reply to me in the Magichome server's #i-need-help channel. We can figure out a time to work together.

**Comment by Zacknetic** [comment]
Hey @edmarts , missed you this afternoon. Ended up working with another dev who I believe helped me solve the problem. Please update to version 1.8.0 and test out your scenes!

**Comment by edmarts** [comment]
Hello Friend! There was something unexpected and I couldn't go online. I just updated and tested. it is perfect!!! Even my node-red automations that didn't work now were perfect !! You rock!!!

**Comment by Zacknetic** [comment]
Absolutely great to hear it! Stop by the Discord server sometime and say hi.

Enjoy!
