### ISSUE TITLE
device found but not registered 

### ISSUE THREAD

**Issue by Suma-xy** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#69]
hello guys, 
I have set up homebridge. I connected my light strip and all was good. But since I reset Homebridge and I wanted to set up my magic home light strip it no longer works, my light strip is in the reachable both locally and from the internet. What can I do in this case?
<img width="1440" alt="Bildschirmfoto 2020-12-10 um 16 46 23" src="https://user-images.githubusercontent.com/48092912/101795112-d805ca00-3b07-11eb-9f76-f35bd052f299.png">

**Comment by Suma-xy** [comment]
[Log.txt](https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/files/5675070/Log.txt)
here is my log

**Comment by isramos** [comment]
@Suma-xy  Please submit the log with Homebridge debug mode enabled.
https://user-images.githubusercontent.com/66505845/90115535-cf35ff00-dd86-11ea-94e9-047662f346ae.png

**Comment by Suma-xy** [comment]
[Debug Log.txt](https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/files/5675526/Debug.Log.txt)
here the debug is enabled

**Comment by isramos** [comment]
That device is no longer showing in the discovery. Is it still showing in the MagicHome app?

**Comment by Suma-xy** [comment]
I restarted Homebridge again. Now it is displayed. By the way the problem can not be my network, I have the bridge and my controller next to the router.
[Ohne Titel 2.txt](https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/files/5675686/Ohne.Titel.2.txt)

**Comment by isramos** [comment]
I don't have a solution, but just want to document my findings.

We broadcast the MagicHome signature  ( 'HF-A11ASSISTHREAD' at port 48899) and your device responds it is model  AK001-ZJ210. Then we asked for more information, sending the QUERY [0x81, 0x8a, 0x8b], but your device did not respond to that.  

You said this device used to work with this plugin?  I Googled 'AK001-ZJ210' and found that is an `RGB SPI addressable controller`  (https://community.athom.com/t/app-magic-home-led-controllers-needs-other-developer/1750/44)  I believe that device is not in our list of supported devices, right  @Zacknetic

**Comment by Zacknetic** [comment]
> I don't have a solution, but just want to document my findings.
> 
> 
> 
> We broadcast the MagicHome signature  ( 'HF-A11ASSISTHREAD' at port 48899) and your device responds it is model  AK001-ZJ210. Then we asked for more information, sending the QUERY [0x81, 0x8a, 0x8b], but your device did not respond to that.  
> 
> 
> 
> You said this device used to work with this plugin?  I Googled 'AK001-ZJ210' and found that is an `RGB SPI addressable controller`  (https://community.athom.com/t/app-magic-home-led-controllers-needs-other-developer/1750/44)  I believe that device is not in our list of supported devices, right  @Zacknetic 
> 
> 
> 
> 

No, it should be supported. I have no way of knowing until it replies its device type back. 

I have an idea of what the issue could be. Possibly the legacy protocol. I will look into it sometime tonight.

**Comment by isramos** [comment]
@Suma-xy can you please clarify. Did you ever get this device to work with the `HomebridgeMagicHome-DynamicPlatform` plugin? If so, what version of the plugin were you using. You know, you can now rollback plugin versions in the new config-ui-x, so you may want to try that out.

**Comment by Suma-xy** [comment]
Hey again. Sorry that I have not printed clearly, but I had no time to write more. Anyway show I had Homebridge on my Raspberry pi 4, there I had installed my light strip with the magic-home plugin, it was the 1.9.1 version. Now I bought a server for home and Homebridge runs on it. It is still the same homebridge version and magic home plugin version. I could control my controller then on the Raspberry pi and now I can't, I tried to whitelist the Mac address of my controller but it still didn't help.  I hope this information will help you.

**Comment by Suma-xy** [comment]
here is again a current log
[Log 11.12.2020 13-55.txt](https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/files/5679241/Log.11.12.2020.13-55.txt)

**Comment by Zacknetic** [comment]
> I could control my controller then on the Raspberry pi and now I can't, 
So to clarify, you mean this plugin worked for you on the raspberry pi, but when running the plugin on the server it doesn't detect it. Correct?

Can you please install the plugin version 1.9.2 on both the server and the pi and see if that works with either of them?

**Comment by Suma-xy** [comment]
> > I could control my controller then on the Raspberry pi and now I can't, 
> 
> 
> 
> So to clarify, you mean this plugin worked for you on the raspberry pi, but when running the plugin on the server it doesn't detect it. Correct?
> 
> 
> 
> Can you please install the plugin version 1.9.2 on both the server and the pi and see if that works with either of them?

Yes, exactly. The plugin worked as it was on the Raspberry Pi. Now it doesn't work on the server. Unfortunately, I can't try it anymore because I've already reset my Raspberry Pi.

**Comment by Zacknetic** [comment]
It would appear the server is behind some complicated network and/or you are using a program such as docker to run HomeBridge. I have no solution for you other than removing those variables.
