### ISSUE TITLE
RGB LED Strip discovered, but throws an error when registering

### ISSUE THREAD

**Issue by cerahmed** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#71]
Hi Zack,

Appreciate your work for this very awesome plugin. I tried to get it to work a few months ago with no luck, came back after a couple of updates and I'm now running into the same issue.

I currently have one MagicHome RGB (4 pins) LED Strip ([LINK](https://www.amazon.com/gp/product/B07333C2WR/ref=ppx_od_dt_b_asin_title_s00?ie=UTF8&psc=1)) connected to the network through the MagicHome app - and is working fine via the app.

After installing this plugin and restarting Homebridge, the log shows the plugin could discover the LED controller successfully but throws an error right after trying to register it:

```
[12/11/2020, 17:45:18] [homebridge-magichome-dynamic-platform] 
Discovered 1 devices.

[12/11/2020, 17:45:18] [homebridge-magichome-dynamic-platform] 1 -Registering existing accessory...
 Display Name: undefined 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ2131' 
Unique ID: 'C82E475FCD06' 
IP-Address: '192.168.1.31' 
Hardware Version: '51' 
Firmware Version: '8' 

[12/11/2020, 17:45:18] [homebridge-magichome-dynamic-platform] platform.ts discoverDevices() accessory creation has thrown the following error: TypeError: accessoryType[existingAccessory.context.device.lightParameters.controllerLogicType] is not a constructor
    at HomebridgeMagichomeDynamicPlatform.registerExistingAccessory (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:404:28)
    at HomebridgeMagichomeDynamicPlatform.discoverDevices (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:159:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  [stack]: 'TypeError: accessoryType[existingAccessory.context.device.lightParameters.controllerLogicType] is not a constructor\n' +
    '    at HomebridgeMagichomeDynamicPlatform.registerExistingAccessory (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:404:28)\n' +
    '    at HomebridgeMagichomeDynamicPlatform.discoverDevices (/usr/lib/node_modules/homebridge-magichome-dynamic-platform/src/platform.ts:159:20)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
  [message]: 'accessoryType[existingAccessory.context.device.lightParameters.controllerLogicType] is not a constructor'
}
[12/11/2020, 17:45:18] [homebridge-magichome-dynamic-platform] 
Registered 0 Magichome device(s). 
New devices: 0 
Cached devices that were seen this restart: 0
Cached devices that were not seen this restart: 0
```

I tried to look for similar issues here, hence tried to prune the accessory and restart - no luck again.
Another thing to note is that the plugin identifies the device as "**GRBWStrip**", whereas it's a 4-pin RGB LED controller.

Appreciate if you can help with this issue.

**Comment by cerahmed** [comment]
I have downgraded to version 1.8.5 as ([LINK](https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/issues/66#issuecomment-741810707)) has suggested, and it works just fine.

**Comment by Zacknetic** [comment]
Hey, thank you for giving me such a detailed report. That was a known bug and has since been addressed   This issue is currently fixed in beta6 and a release to 1.9.2 later today will implement those changes.

I highly suggest you update when you see it. You have nothing to lose as we’ve created a migration function to allow for seamless updates.

**Comment by Zacknetic** [comment]
Let me know if that beta works out for you. We're on 11 now ...

**Comment by cerahmed** [comment]
Hi again, I have just updated to 1.9.2-beta-1, and the log threw the following error:

```
[12/12/2020, 13:13:26] [homebridge-magichome-dynamic-platform] 
Discovered 1 devices.

[12/12/2020, 13:13:26] [homebridge-magichome-dynamic-platform] 1 -Registering existing accessory...
 Display Name: 'Upper Room Hidden Lights' 
Controller Logic Type: 'GRBWStrip'  
Model: 'AK001-ZJ2131' 
Unique ID: 'C82E475FCD06' 
IP-Address: '192.168.1.31' 
Hardware Version: '51' 
Firmware Version: '8' 

[12/12/2020, 13:13:26] [homebridge-magichome-dynamic-platform] [3] The controllerLogicType does not exist in accessoryType list. controllerLogicType= GRBWStrip
[12/12/2020, 13:13:26] [homebridge-magichome-dynamic-platform] 
Registered 0 Magichome device(s). 
New devices: 0 
Cached devices that were seen this restart: 0
Cached devices that were not seen this restart: 0
```

Clearly, the LED Strip stopped working.

Thanks.

**Comment by djweinhagen** [comment]
Hi Zach, Thanks for your work on this plugin. The new beta, 1.9.2b13, has fixed my issue(#66)! Super happy to have it working again.

**Comment by Zacknetic** [comment]
@djweinhagen, very happy to hear that. Thanks for letting me know!

@cerahmed Please update to v1.9.2. This should solve your issue. Let me know.

**Comment by cerahmed** [comment]
Updated to v1.9.2 and it works perfectly now!
Many thanks for the quick implementation of the fix.

**Comment by Zacknetic** [comment]
Very happy to hear.
