### ISSUE TITLE
Lights not working as intended with automations

### ISSUE THREAD

**Issue by WummoFTW** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#76]
**Issue:**
When I try to use my LED strips in automations (HomeKit native or even Shortcuts App) they are still shown as off in HomeKit.

**Reproduction:**
Reproduction is easy just create a simple "turn on LED strip" shortcut in Shortcuts and the bug should appear, your light is on, but HomeKit shows it as off. 

**Additional context:**
I don't know if this is related, but MagicHome devices have a tendency to be kind of slow or even unresponsive in Control Center too

Hardware: _Raspberry Pi 3b+_
OS: _HOOBS_ 
OS Version: _buster_
_HOOBS version 3.3.1
Homebridge MagicHome Dynamic Platform version 1.9.2_

**Comment by Zacknetic** [comment]
Hello, I've noticed this issue in my own setup as well. I assume what is happening is the lights are reporting back an incorrect state, thus messing up scenes.  I know this is cliché, but could you please unplug your light (remove it from the socket entirely / unplug power source ) and plug it back in. Sometimes that helps reset the device's state. 

 Let me know, thanks,
