### ISSUE TITLE
Homebridge crash

### ISSUE THREAD

**Issue by BetoRn** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#8]
hi, i have just installed the plugin and it's crashing homebridge, here's the log

Jul 12 20:32:58 raspberrypi homebridge[2575]: [7/12/2020, 8:32:58 PM] Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
Jul 12 20:32:58 raspberrypi homebridge[2575]:     at healthCheck (dgram.js:663:11)
Jul 12 20:32:58 raspberrypi homebridge[2575]:     at Socket.close (dgram.js:545:3)
Jul 12 20:32:58 raspberrypi homebridge[2575]:     at Timeout.setTimeout (/usr/local/lib/node_modules/homebridge-magichome-dynamic-platform/dist/magichome-interface/Discover.js:39:24)
Jul 12 20:32:58 raspberrypi homebridge[2575]:     at listOnTimeout (timers.js:324:15)
Jul 12 20:32:58 raspberrypi homebridge[2575]:     at processTimers (timers.js:268:5)
Jul 12 20:32:58 raspberrypi homebridge[2575]: [7/12/2020, 8:32:58 PM] Got SIGTERM, shutting down Homebridge...

thanks!

**Comment by Zacknetic** [comment]
Hi, thank you for posting your issue with your log. 

Has this issue always occurred or only in the list recent update of this plugin?

I will look into this but at first glance I can't see why this would happen. 

Somehow the scan function is causing the program to crash.

**Comment by BetoRn** [comment]
This is the first time I have tried the plugin

**Comment by Zacknetic** [comment]
May you please upload your config.json and your entire homebridge.log?
