### ISSUE TITLE
Unknown device version number: '8'

### ISSUE THREAD

**Issue by ZenoGillis** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#80]
Trying to use your plugin to auto detect the LED-controllers but both of them keep giving me an error, here is part of the log file: 

`[16/01/2021, 17:43:31] [homebridge-magichome-dynamic-platform] Attempting to assign controller to new device: UniqueId: 'F4CFA23EA40E' 
IpAddress '192.168.0.215' 
Model: 'AK001-ZJ2104'
Hardware Version: '8' 
Device Type: '1'`

Is there anything I can do to resolve this issue?

**Comment by Zacknetic** [comment]
Hi,

I will need some more information before I can begin solving this issue.  Could you please follow the [bug report template](https://github.com/Zacknetic/HomebridgeMagicHome-DynamicPlatform/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and I will be able to help you further.
