### ISSUE TITLE
Add an option to "just white"

### ISSUE THREAD

**Issue by heyjhoow** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#93]
I'm working on some things for my bedroom, and I was wondering if there's a way to set a RGBW controller to show just a Warm White/Cold White (as user chooses on Homebridge) controller on Homekit.

I really like to use LED strips as guide lights on my projects, and the option to "disable" the other colors on the strip would be great

**Comment by Zacknetic** [comment]
Hello,

You can achieve this by changing the “colorOffThresholdSimultaniousDevices” setting to 100 and clicking save.

**Comment by heyjhoow** [comment]
Thanks for the help!

I'll try this ASAP!!!
