### ISSUE TITLE
[BUG] Concise Description of the Issue

### ISSUE THREAD

**Issue by vlforte** [Zacknetic/HomebridgeMagicHome-DynamicPlatform#96]
Is it possible to manually add devices? I have all my devices on a separate vlan, thus auto discovery won't work unless I manually add the devices IP address.

**Comment by Zacknetic** [comment]
This feature is not within the scope of the plugin. The plugin _does_ search on all available subnets.  If that doesn't work on your system then you may have to move your devices off the vlan or use tom's MagicHome plugin. I believe his allows manual configuration.
